### PR TITLE
Calls to setWeights() should not use array creation for varargs parameters.

### PR DESCRIPTION
**Pull request by RishiKumarRay**

### CODE REVIEW

**Review by nilsschmidt1337 — COMMENTED** [review]
Hi @RishiKumarRay , can you please change the commit message to "Fixed issue #866." instead of "refactor Calls to setWeights()"?

**Comment by RishiKumarRay** [comment]
@nilsschmidt1337 please check now

**Comment by nilsschmidt1337** [comment]
@RishiKumarRay now you have to "squash" the three commit into one commit do a `git push --force-with-lease`.

**Comment by RishiKumarRay** [comment]
@nilsschmidt1337 Is it fine now? Thanks i have learnt many things

**Comment by nilsschmidt1337** [comment]
@RishiKumarRay thanks! I added a GitHub actions run. There seems to be a problem.

**Comment by RishiKumarRay** [comment]
@nilsschmidt1337 i went through the error , is it this semicolon ? 
Screenshot from 2022-01-22 00-30-36

**Comment by nilsschmidt1337** [comment]
@RishiKumarRay yes! I think you spotted the error. Congratulations!

**Comment by RishiKumarRay** [comment]
@nilsschmidt1337 Thanks, PLease check the workflow now, I hope it will pass now

**Comment by nilsschmidt1337** [comment]
@RishiKumarRay great! I will squash and merge the PR now.

**Comment by RishiKumarRay** [comment]
@nilsschmidt1337 Thanks, Let me know if you align me any other task , Maybe in future. I will be happy to do that.

**Review by nilsschmidt1337 — APPROVED** [review]

**Comment by nilsschmidt1337** [comment]
@RishiKumarRay one more tip: do not always push with force! 😄
`git push --force-with-lease` is usually used only if you want to rewrite the git history of your repository.
Normally, you should consider using `git push` as usual.

**Pull request merged**
